version: "3"

services:
  voting-app:
    build: ./
    restart: always
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 1m
      timeout: 10s
      retries: 3
